[platformio]
default_envs = m5stickc_plus2

[env:m5stickc_plus2]
platform = espressif32
board = m5stick-c
framework = arduino

; El sketch está en src/m5-stick/ (ruta relativa a src/)
build_src_filter = +<m5-stick/*>

monitor_speed = 115200
upload_speed = 921600

lib_deps =
  m5stack/M5Unified @ ^0.2.5

build_flags =
  -DARDUINO_M5Stick_C_PLUS2
  -DCORE_DEBUG_LEVEL=0
